# Generated by Django 6.0.5 on 2026-05-19 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_producida', models.FloatField()),
                ('tiempo_real_horas', models.FloatField()),
                ('es_anomalia', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=200)),
                ('prod_esperada', models.FloatField()),
                ('tiempo_estimado_horas', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Maquina',
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='progreso',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_entrega',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produccion.cliente'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='produccion.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='registroproduccion',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.tarea'),
        ),
    ]
