# Generated by Django 4.2.7 on 2026-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
