# Generated by Django 6.0.5 on 2026-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0002_alter_maquina_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
